src/main/java/com/navercorp/arcus/spring/ArcusClientFactoryBean.java

ARCUS front cache 에 copyOnRead / CopyOnWrite 옵션을 줄 수 있도록 기능을 추가함.
(default 는 둘 다 false 로 설정)
review

Feature : Added copyOnWrite / copyOnRead to ARCUS front cache

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProvider.java
src/main/java/com/navercorp/arcus/spring/concurrent/KeyLockProvider.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
src/test/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProviderTest.java

https://github.com/naver/arcus-spring/pull/7 에서 많은 commit으로 리뷰가 불가하여
다시 PR을 보내드립니다.

FEATURE: supports spring version 4.3.0

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/resources/arcus_spring_arcusCacheManager_test.xml

- ArcusCacheManager
- ArcusClientPool 객체를 재사용할 수 있도록 수정
- 누락된 prefix 속성 추가
- ArcusCacheManagerTest
- ArcusCacheManager bean 생명주기에 따른 캐시 초기화 테스트 (loadCaches 테스트)

FEATURE: Initializing ArcusCacheManager using configuration

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusStringKey.java
src/main/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProvider.java
src/main/java/com/navercorp/arcus/spring/concurrent/KeyLockProvider.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheWithAnnotationTest.java
src/test/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProviderTest.java

코드 수정 날짜를 기준으로 라이센스 업데이트하였습니다.
@minkikim89 
리뷰 바랍니다.

LEGAL: Update copyright

---

pom.xml

 FEATURE: upgrade to the latest log4j version (2.8.2 => 2.13.3)

---

README.md
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/SimpleStringKeyGenerator.java
src/main/java/com/navercorp/arcus/spring/cache/StringKeyGenerator.java
src/test/java/com/navercorp/arcus/spring/cache/KeyGeneratorTest.java

oldStringKeyGenerator를 복구하였고, 선택적으로 사용할 수 있도록 하였습니다.
xml에서 generator로 선택하여 사용할 수 있습니다.

CLEANUP: added old string key generator for the backward compatibility

---

README.md
pom.xml
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/StringKeyGenerator.java

javadoc 관련하여 에러 발생하는 부분 수정하였습니다.

DOC: fixed the javadoc generation errors

---

pom.xml

junit 버전 4.12 => 4.13.1 으로 업그레이드하였습니다.

TEST: Bump junit from 4.12 to 4.13.1

---

pom.xml

arcus-java-client 1.11.4에서 1.12.0으로 변경하였습니다.

FEATURE: upgrade arcus-java-client version (1.11.4 => 1.12.0)

---

pom.xml
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java

java-client 최신 버전으로 업그레이드 하였습니다.
업그레이드 과정 중에 테스트 코드에 빌드 에러가 발생하여 함께 수정하였습니다.

FEATURE: upgrade arcus-java-client version (1.12.0 => 1.13.0)

---

src/main/java/com/navercorp/arcus/spring/ArcusClientFactoryBean.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusStringKey.java
src/main/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProvider.java

로그의 오타 수정과 함께 java lint warning이 발생되는 코드들을 제거하였습니다.

CLEANUP: remove lint warnings

---

README.md

front caching 기능 설명을 위해 README.md 업데이트 하였습니다.
변경된 마크 다운은 아래 링크로 참조 가능합니다.
https://github.com/hjyun328/arcus-spring/tree/develop#front-cache

DOC: update README.md for front caching

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java

operation timeout이 자주 발생되는 현상을 고려하여 default operation timeout을 300ms => 700ms로 변경하였습니다.

FEATURE: change default operation timeout to 700ms

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java

front, arcus cache의 hit 정보를 로거로 확인할 수 있도록 추가하였습니다.

FEATURE: add cache hit log

---

pom.xml

log4j2에 보안 취약점이 존재해 업그레이드하였습니다.

FEATURE: upgrade log4j version for security vulnerabilities

---

README.md

언어에 따른 syntax highlight 기능을 활성화했습니다.

DOC: Enable syntax highlight for source codes in README.md

---

README.md

- gradle version에 따른 script 변경 사항 반영(compile -> implementation)

DOCS:fix gradle Getting Started

---

ChangeLog
README.md
pom.xml

1.13.4 릴리즈 커밋입니다.
maven repo에 arcus-java-client 1.13.4가 release 된 뒤에 merge 바랍니다.

version 1.13.4

---

README.md

- Front Cache Configuration에 ArcusCacheConfiguration를 사용하는 방식 추가하였습니다.

DOC: Add ArcusCacheConfiguration for Front Cache.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java

- prefix 키 생성이 명확하게 구분되어 있지 않아 메서드 분리하여 처리하도록 변경하였습니다.

INTERNAL: generate prefix key once

---

docs/01-arcus-cache-basics.md
docs/02-arcus-spring-concept.md
docs/03-arcus-spring-usage.md
docs/04-arcus-spring-notes.md

https://github.com/naver/arcus-spring/issues/58
사용자 가이드 문서를 작성했습니다.
`01-arcus-cloud-basics.md` 파일은 arcus-java-client에서 가져왔습니다.
https://github.com/uhm0311/arcus-spring/tree/uhm0311/develop3/docs
위 링크로 들어가서 문서를 보면 보기 쉽습니다.

DOC: Add user guide.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java

Ident가 1단계 더 들어가 있는 부분을 제거했습니다.

CLEANUP: Remove unnecessary additional indents.

---

pom.xml
src/main/java/com/navercorp/arcus/spring/ArcusTemplate.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java
src/main/java/com/navercorp/arcus/spring/callback/ArcusCallBack.java
src/main/java/com/navercorp/arcus/spring/callback/AsycGetMethod.java
src/main/java/com/navercorp/arcus/spring/callback/AsyncLopDeleteByIndexMethod.java
src/main/java/com/navercorp/arcus/spring/callback/AsyncLopDeleteByRangeMethod.java
src/main/java/com/navercorp/arcus/spring/callback/DeleteMethod.java
src/main/java/com/navercorp/arcus/spring/callback/SetMethod.java
src/test/java/com/navercorp/arcus/spring/ApplicationContextLoadTest.java
src/test/java/com/navercorp/arcus/spring/ArcusTemplateTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheConfig.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheWithAnnotationTest.java
src/test/java/com/navercorp/arcus/spring/cache/ExternalizableTestClass.java
src/test/java/com/navercorp/arcus/spring/cache/KeyGeneratorTest.java
src/test/java/com/navercorp/arcus/spring/cache/SerializableTestClass.java
src/test/java/com/navercorp/arcus/spring/cache/front/DefaultArcusFrontCacheTest.java
src/test/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProviderTest.java
src/test/resources/arcus_spring_arcusCache_annotation_test.xml

컴파일 워닝과 인텔리제이 워닝을 제거하는 커밋입니다.
릴리즈를 위해 컴파일 옵션에 모든 워닝을 에러로 취급하도록 했으며, 이를 통해 발생하는 에러를 제거하기 위함입니다.
기능이나 로직적으로 바뀐 부분은 전혀 없습니다.
본 PR이 반영되고 나면 CI 설정을 추가할 예정입니다.

CLEANUP: Refactored codes to remove compile warnings and IDE warnings.

---

.github/workflows/ci.yml

TEST: Add Github action CI config.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-refactoring-request.md
.github/PULL_REQUEST_TEMPLATE.md

DOC: Add Github issue and PR templates.

---

ChangeLog
README.md
docs/03-arcus-spring-usage.md
pom.xml

version 1.13.5

---

.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
src/main/java/com/navercorp/arcus/spring/ArcusClientFactoryBean.java
src/main/java/com/navercorp/arcus/spring/ArcusTemplate.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java
src/main/java/com/navercorp/arcus/spring/cache/SimpleStringKeyGenerator.java
src/main/java/com/navercorp/arcus/spring/cache/StringKeyGenerator.java
src/main/java/com/navercorp/arcus/spring/cache/front/EhArcusFrontCache.java
src/main/java/com/navercorp/arcus/spring/callback/ArcusCallBack.java
src/main/java/com/navercorp/arcus/spring/callback/AsycGetMethod.java
src/main/java/com/navercorp/arcus/spring/callback/AsyncLopDeleteByIndexMethod.java
src/main/java/com/navercorp/arcus/spring/callback/AsyncLopDeleteByRangeMethod.java
src/main/java/com/navercorp/arcus/spring/callback/DeleteMethod.java
src/main/java/com/navercorp/arcus/spring/callback/SetMethod.java
src/test/java/com/navercorp/arcus/spring/ApplicationContextLoadTest.java
src/test/java/com/navercorp/arcus/spring/ArcusTemplateTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheConfig.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheWithAnnotationTest.java
src/test/java/com/navercorp/arcus/spring/cache/KeyGeneratorTest.java
src/test/java/com/navercorp/arcus/spring/cache/front/DefaultArcusFrontCacheTest.java
src/test/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProviderTest.java

- https://github.com/jam2in/arcus-works/issues/547
- `.idea/codeStyles/Project.xml` : 설정 파일입니다.
- `.idea/codeStyles/codeStyleConfig.xml`
-  설정 파일을 IDE가 자동으로 인식하여 사용하게 해주는 파일입니다.
- 예전에 처음 arcus-java-client에 import 설정을 적용할 때 이 파일을 포함하지 않아서 개발자마다 위의 `Project.xml` 파일을 불러오는 과정이 필요했습니다.
- 이 파일이 있으면 clone을 받을 때마다 기본값으로  `Project.xml` 설정이 사용 상태가 됩니다.

INTERNAL: Adjust new auto import setting.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java

- https://github.com/jam2in/arcus-works/issues/564
- ArcusCacheManager를 사용할 때도 wantToGetException을 설정할 수 있도록 합니다.

FEATURE: Add wantToGetException field to ArcusCacheConfiguration class.

---

src/main/java/com/navercorp/arcus/spring/ArcusClientFactoryBean.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java

- 
- Deprecated 클래스, 테스트 코드를 제외하고 불필요한 개행을 제거합니다.

CLEANUP: Remove unnecessary line feeds.

---

.github/workflows/ci.yml
pom.xml
src/main/java/com/navercorp/arcus/spring/cache/ArcusStringKey.java
src/test/java/com/navercorp/arcus/spring/ApplicationContextLoadTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheWithAnnotationTest.java
src/test/java/com/navercorp/arcus/spring/cache/KeyGeneratorTest.java
src/test/java/com/navercorp/arcus/spring/cache/front/DefaultArcusFrontCacheTest.java
src/test/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProviderTest.java

- https://github.com/jam2in/arcus-works/issues/566
- JDK 버전과 Maven 의존성 버전을 업그레이드합니다.
- 테스트 코드 관련 Maven 의존성과 같이 인터페이스가 변경된 부분은 변경된 인터페이스를 반영합니다.

INTERNAL: Upgrade the JDK and dependencies.

---

src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- 
- 테스트코드에서 deprecated된 메서드를 사용하지 않도록 변경합니다.

TEST: remove usage of deprecated methods

---

pom.xml

- 
- pom.xml파일에 잘못 들어갔던 zookeeper 의존성을 제거합니다.

FIX: remove zookeeper dependency

---

README.md
docs/03-arcus-spring-usage.md
src/main/java/com/navercorp/arcus/spring/ArcusCacheConfigurationFactoryBean.java
src/main/java/com/navercorp/arcus/spring/ArcusClientFactoryBean.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/test/resources/arcus_spring_arcusCacheManager_test.xml
src/test/resources/arcus_spring_arcusCache_annotation_test.xml
src/test/resources/arcus_spring_arcusCache_test.xml
src/test/resources/arcus_spring_basic_context_test.xml

- https://github.com/jam2in/arcus-works/issues/608
- xml에서 사용 가능한 ArcusCacheConfigurationFactoryBean를 추가합니다.

INTERNAL: add ArcusCacheConfigurationFactoryBean

---

ChangeLog
README.md
docs/03-arcus-spring-usage.md
pom.xml

version 1.14.0

---

ChangeLog

- jam2in/arcus-works#708
- ChangeLog 형식을 수정합니다.

DOC: Update ChangeLog format

---

.github/workflows/ci.yml

- java client와 동일하게 CI 파일을 수정했습니다.
-

FIX: use ubuntu latest version to prevent error and tidy ci.yml

---

.github/workflows/ci.yml

- 
- 이전 PR에서 미처 추가하지 못한 부분을 수정했습니다.

FIX: add types in ci.yml
