naver/arcus-spring

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusStringKey.java
src/main/java/com/navercorp/arcus/spring/cache/StringKeyGenerator.java

Add key's hashcode using each param's hashcode at StringKeyGenerator,
Add whole key string's hashcode at ArcusCache.createArcusKey,
Add ArcusStringKey class to distinguish given key type.
Closes issue #4.

Add hashcode to generating key strings

---

pom.xml
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java

최신 Spring 버전에서 arcus-spring을 사용하려고 했으나 몇 가지 어려움이 있어 필요한 부분만 따로 구현해서 사용했었습니다.
사용이 어려웠던 점 중 하나가 캐시별 TTL 설정이나 미리 정의하지 않은 캐시에 대한 생성을 담당하는 `CacheManager` 구현체의 부재였습니다.
이번에 버전업 작업을 하시는 것으로 보여 자체적으로 구현한 `CacheManager` 구현체를 정리해 PR 보냅니다.
우선 필요한 기능만 넣은 상태여서 최소한의 기능만 있는데, 참고만 하시면 될 것 같습니다.
추후 Builder 패턴으로 생성하게 하거나 Configuration 파일을 별도로 만들어서 캐시별로 설정할 수 있게 하는 등의 고도화도 가능할 것 같습니다.
#8 기준으로 Spring / Junit dependency 버전을 올렸고, `ArcusCache`의 신규 method 구현은 비워놓았습니다.
테스트의 경우 자체적으로 "127.0.0.1:2181"에 test arcus를 띄우는 방법으로 테스트하시는 것 같은데 이 방법을 몰라서 실행해보지는 못했습니다.

FEATURE: Implement ArcusCacheManager

---

pom.xml

https://support.sonatype.com/hc/en-us/articles/360041287334
2020년 1월 15일부터 maven repo를 https로 변경해야 합니다.
현재 pom.xml에서 dependency를 받을 수 없는 상태로 pom.xml을 https로 변경하였습니다.

FEATURE: change maven repo because it no longer supports insecure HTTP

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java

prefix가 설정된 경우, 불필요한 key 생성 코드가 있어 GC 부담 제거를 위해 변경하였습니다. 
Issue: https://github.com/naver/arcus-spring/issues/24

ENHANCE: do not create arcus key twice.

---

pom.xml

arcus-java-client 1.13.0 버전에 하위 호환성 및 transcoder 이슈가 존재하여 이를 해결한 버전으로 업그레이드 하였습니다.

FEATURE: upgrade arcus-java-client version (1.13.0 => 1.13.2)

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusStringKey.java
src/main/java/com/navercorp/arcus/spring/cache/StringKeyGenerator.java

arcus-spring에서 제공하는 키 생성 클래스인 StringKeyGenerator, SimpleStringKeyGenerator를 다른 Cache 구현체에서 사용하면, 반복적인 Cache Miss가 발생하여, 이를 수정하였습니다.
만약 아래와 같이 응용 코드에서 ArcusCacheManager, EhCacheManager를 둘 다 사용하고, arcus-spring에서 제공되는 StringKeyGenerator를 사용할 경우 
```java
import com.navercorp.arcus.spring.cache.StringKeyGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.CachingConfigurer;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.cache.interceptor.CacheErrorHandler;
import org.springframework.cache.interceptor.CacheResolver;
import org.springframework.cache.interceptor.KeyGenerator;
import …
```

FEATURE: support key generator for other cache implementations

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java
src/main/java/com/navercorp/arcus/spring/cache/front/ArcusFrontCache.java
src/main/java/com/navercorp/arcus/spring/cache/front/DefaultArcusFrontCache.java
src/main/java/com/navercorp/arcus/spring/cache/front/EhArcusFrontCache.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
src/test/java/com/navercorp/arcus/spring/cache/front/DefaultArcusFrontCacheTest.java

기존 arcus-java-client에는 front cache 기능을 지원하지만, front cache 설정이 전역으로 설정되어 캐시 대상별로 세부 설정이 불가능한 문제가 있습니다.
이를 위해 ArcusCache 레벨에서 front cache 기능이 수행될 수 있도록 추가하였습니다. 
- Arcus 캐시 노드 다운시에도 front cache 기능이 동작 가능 (ArcusCache의 `forceFrontCaching`를 true로 설정해야 함)
- ArcusCache 별로 front cache의 expire time을 설정
- ArcusCache 별로 front cache의 세부 설정 가능
추가로, 로그 레벨이 일관성 없게 설정되어 error 메시지 레벨은 info로 변경하였습니다.

FEATURE: support front cache for ArcusCache

---

pom.xml

arcus-java-client 의존성 버전을 1.13.4로 업그레이드하면서, naver maven repo가 아닌 jam2in maven repo를 사용하도록 변경했습니다.

FEATURE: upgrade arcus-java-client version (1.13.2 => 1.13.4)

---

README.md

설치 가이드에서 naver maven repo가 아닌 jam2in maven repo를 사용하는 것을 가이드 하도록 변경했습니다.

DOC: Change installation guide from naver maven repo to jam2in maven repo.

---

pom.xml
src/main/java/com/navercorp/arcus/spring/cache/SimpleStringKeyGenerator.java
src/main/java/com/navercorp/arcus/spring/cache/StringKeyGenerator.java

Spring5부터 [@NonNullApi](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/lang/NonNullApi.html)를 통해 검사되고 있는 Jsr-305지원하도록 [@Nullable](https://www.javadoc.io/doc/com.google.code.findbugs/jsr305/latest/javax/annotation/Nullable.html) 어노테이션을 추가합니다.
실제로 SimpleStringKeyGenerator에서는 target, method는 사용되지 않아서 Wrapper Class를 만들어 쓰는 경우 null을 주입해야하나, 
어노테이션이 없어서 스프링에서 사용시 NonNull로 판단되어 코틀린에서 사용시 `freeCompilerArgs = listOf("-Xjsr305=strict")`지정시 컴파일 오류가 발생합니다.
따라서 해당 클래스에 Nullable어노테이션을 추가하고자합니다.

FEATURE: Add @Nullable annotation on SimpleStringKeyGenerator generate method for support JSR-305

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java

Spring-core 6.1에서 제거된 Assert.notNull(Object)를 Assert.notNull(Object, String) 으로 수정합니다.

FIX: Fix deprecated spring assert

---

src/main/java/com/navercorp/arcus/spring/ArcusClientFactoryBean.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusStringKey.java
src/main/java/com/navercorp/arcus/spring/cache/front/EhArcusFrontCache.java

https://github.com/naver/arcus-spring/pull/61
위 PR의 후속 PR 입니다.
KeyGenerator 구현체 뿐만 아니라, `@Deprecated`가 붙지 않은 모든 클래스에 null 사용 가능 여부를 어노테이션으로 명시했습니다.
ArcusCache 클래스의 put 관련 메소드 중, putIfAbsent() 메소드에 한해 value에 `@NonNull`이 붙어 있는 것은 해당 메소드에서만 value가 null일 경우 Exception을 던지기 때문입니다.
다른 put 관련 메소드에서는 value에 대해 null 체크를 한 후 null이면 로그를 찍고 캐싱 로직을 수행하지 않습니다.

INTERNAL: Add @Nullable annotation.

---

src/main/java/com/navercorp/arcus/spring/cache/SimpleStringKeyGenerator.java
src/main/java/com/navercorp/arcus/spring/cache/StringKeyGenerator.java

https://github.com/naver/arcus-spring/issues/50
SimpleKeyGenerator와 같은 형태의 인터페이스를 하나 추가했습니다.
단, arcus-spring의 KeyGenerator 구현체에서 생성하는 객체는 명시적으로 ArcusStringKey 타입임을 나타내기 위해 반환 타입을 Object가 아닌 ArcusStringKey로 했습니다.

FEATURE: Add generateKey() method to KeyGenerator implementations.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java

ArcusCacheManager에서 사용하기 위한 용도의 생성자를 ArcusCache에 추가했습니다.
ArcusCache에 내부 동작과 인자가 없는 public 생성자를 추가한 이유는 별도의 생성자가 없는 경우에 내부 동작과 인자가 없는 public 생성자가 컴파일 과정에서 자동으로 생기는데, 이번에 default 접근 제한자를 갖는 생성자를 추가하여 내부 동작과 인자가 없는 public 생성자를 유지하기 위해서는 명시적으로 선언해야 하기 때문입니다

INTERNAL: Add constructor that is used by ArcusCacheManager to ArcusCache.

---

src/main/java/com/navercorp/arcus/spring/ArcusTemplate.java

로컬 테스트에서 발견하지 못했던 Deprecated warning이 CI 테스트에서 발견되어 제거합니다.

FIX: Remove deprecated warnings to fix CI test.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- [Spring Cache Abstraction 공식 문서](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/cache/Cache.html#get(java.lang.Object,java.util.concurrent.Callable))에 따르면, get 메서드에서 Callable을 인자로 받고 call() 메서드를 수행하면 ValueRetrievalException 이 반환되어야 한다고 합니다.
- call() 메서드를 호출할 때 try-catch 문으로 감싸고 예외가 발생하면 ValueRetrievalException가 반환되도록 변경합니다.

FIX: throw ValueRetrievalException when valueLoader throws Exception

---

pom.xml
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- https://github.com/jam2in/arcus-works/issues/541
- ArcusCache 클래스가 AbstractValueAdaptingCache 클래스를 상속받도록 변경합니다. 이를 위해 lookup 메서드를 재정의했습니다.
- 이를 통해 ArcusCache 클래스에서 기본적으로 AbstractValueAdaptingCache 클래스의 get 메서드가 사용됩니다. 그리고 이 때 NullValue 객체 조회 시 null을 반환해주게 됩니다.
- ArcusCacheConfiguration 클래스에서는 cacheNullValues 속성을 설정할 수 있도록 합니다.
- 기존에 `get(Object key)` 메서드에서는 wantToGetException 속성이 유효했지만, 현재는 해당 설정이 무효하여 예외가 발생하면 그대로 전파됩니다.

INTERNAL: get NullValue instance from arcus server

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- https://github.com/jam2in/arcus-works/issues/564
- 주간회의에서 논의한 대로 wantToGetException의 기본값을 false로 설정하고, 캐시 연산 시 항상 wantToGetException을 사용합니다.
- 일부 테스트 코드가 wantToGetException의 기본값이 true인 경우를 상정하고 만들어져 있어서 해당 테스트 코드 수행 전에 wantToGetException을 true로 설정합니다.

FIX: Set default value of wantToGetException to false and fix inconsistent exception handling.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java

- https://github.com/naver/arcus-spring/pull/80#discussion_r1630587396
- 모든 로그 메세지에서 캐시 서버에 저장하려는 값의 타입을 제거합니다.

INTERNAL: Remove value type in put log message.

---

src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- Future 객체를 반환하도록 만드는 Mock 메소드로 asnycGet()이 아닌 get()을 사용하고 있다.
- get()이 아닌 asyncGet()으로 변경

TEST: Fix wrong mock of ArcusClientPool.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- Exception이 발생하진 않았으나 연산이 실패한 경우, OperationStatus를 확인하지 않으면 정확한 연산 실패 원인을 알 수 없다.
- Exception이 발생하진 않았으나 연산이 실패한 경우, OperationStatus를 워닝 로그로 출력합니다.
- 로그 레벨은 임의로 우선 워닝으로 설정했으나 더 적합하다고 생각하는 로그 레벨이 있다면 의견 주세요.

INTERNAL: Add operation status message to log when operation is not successful.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java

- 동일한 의미를 갖는 필드의 기본값을 리터럴로 관리할 경우, 한 쪽만 값을 변경했을 때 다른 쪽의 값이 달라 문제가 될 수 있다.
- 
- wantToGetException 필드의 기본값을 static final로 선언하고 이를 사용하게 합니다.
- wantToGetException 필드가 계속 유지될지 말지에 관계 없이, 적어도 유지되는 동안에는 기본값을 바꾸었을 때의 휴먼 에러를 줄이기 위한 커밋입니다.

INTERNAL: Change default value of wantToGetException from literal to static final constant.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java

- putIfAbsent() 메소드 내에서 캐시 키가 이미 존재하는 경우 해당 캐시 아이템을 반환합니다.
- 이 과정에서 지난번에 적용된 NullValue를 읽는 기능이 적용되지 않았습니다.
- putIfAbsent() 메소드에서도 NullValue를 읽는 기능을 적용합니다.
- toValueWrapper() 메소드는 부모 클래스인 AbstractValueAdaptingCache에 포함되어 있으며, Spring Framework v4.3.10을 포함한 이후의 구현은 항상 다음과 같습니다.
```java
protected Object fromStoreValue(Object storeValue) {
if (this.allowNullValues && storeValue == NullValue.INSTANCE) {
return null;
}
return storeValue;
}
protected Cache.ValueWrapper toValueWrapper(Object storeValue) {
return (storeValue != null ? new SimpleValueWrapper(fromStoreValue(storeValue)) : null);
}
```

FIX: When cache key already exists in putIfAbsent, convert NullValue to null if allow null values.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- putIfAbsent() 메소드에서 null을 반환하는 것은 캐시 아이템 저장을 성공했을 때인데, 캐시 연산 도중 Exception 발생 시 null을 반환한다.
- 캐시 연산 도중 Exception 발생 시 wantToGetException 값이 false인 경우에는 원본 데이터를 그대로 반환합니다.

FIX: Read and return value from cache server when putIfAbsent has failed if wantToGetException is false.

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- 
릴리즈 전 마지막 커밋으로, 아래의 사항을 반영합니다.
- 불필요한 import문 제거
- 불필요한 `@SuppressWarnings` 어노테이션 제거
- 필요한 `@SuppressWarnings`의 경우 메소드 단위로 적용되어 있으면 클래스 단위로 통합
- `String#toString()` 메소드 호출 제거

CLEANUP: Refactored to remove unnecessary codes or redundancies.

---

ChangeLog
README.md
docs/03-arcus-spring-usage.md
pom.xml

version 1.13.6

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
src/test/resources/arcus_spring_arcusCache_test.xml

- https://github.com/jam2in/arcus-works/issues/541
- put, putIfAbsent에서 NullValue를 저장하는 기능을 추가합니다.
- `getSynchrinozed(...)`에서 기존에는 createArcusKey의 결과인 String을 사용해 lock을 잡고 loadValue에도 넘겨 사용했었는데, 이런 방식으로는 같은 클래스의 public 메서드인 put을 사용할 수 없어 putValue를 직접 사용해야만 했습니다. 따라서 createArcusKey를 put 메서드 내부에서만 호출하게 하고 나머지 부분에서는 key를 그대로 사용하도록 하여 메서드 로직을 간결하게 만들었습니다.
- `putIfAbsent(...)` 에서 arcus java client API를 사용하는 부분을 따로 메서드로 분리했습니다.

INTERNAL: put NullValue instance to Arcus and frontCache

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- 
- get synchronized 시에 호출되는 putValue 메서드를 put 메서드로 변경하여 중복되는 키 생성, 예외 잡는 코드를 줄입니다.
- 이로 인해 Lock의 대상 객체를 String key에서 Object key로 변경하였습니다.

REFACTOR: use put method when get synchronized

---

docs/02-arcus-spring-concept.md
docs/03-arcus-spring-usage.md
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java

- https://github.com/naver/arcus-spring/pull/98 에서 파생된 PR입니다.
- serviceId 값을 사용하지 않을 때 빈 문자열`""`를 지정하는데, 이를 기본값으로 두도록 합니다.
- 이를 통해 DefaultCacheConfiguration을 사용자가 지정할 때 new ArcusCacheConfiguration() 만 호출해도 이미 세팅된 기본값으로 동작할 수 있습니다. 기존에는 configuration의 setServiceId를 통해 반드시 빈 문자열을 지정해줘야만 ArcusCache가 빈으로 등록되었습니다.

INTERNAL: set empty string as serviceId's default value

---

pom.xml
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerBuilderTest.java

- https://github.com/jam2in/arcus-works/issues/601
- 현재 대부분의 CacheManager 구현체가 상속받고 있는 AbstractTransactionSupportingCacheManager를 상속받도록 변경했습니다. 이에 따라 spring-context-support, spring-tx 의존성이 추가되었습니다.
- CacheManager 빌더를 추가했습니다.
- ArcusCacheConfiguration에 default config를 얻을 수 있는 메서드를 추가했습니다. 이를 통해 빌더를 사용하면 반드시 default config를 입력하지 않아도 됩니다.

INTERNAL: add builder and transaction for ArcusCacheManager

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/test/java/com/navercorp/arcus/spring/ApplicationContextLoadTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerBuilderTest.java
src/test/resources/arcus_spring_arcusCache_annotation_test.xml
src/test/resources/arcus_spring_arcusCache_test.xml
src/test/resources/arcus_spring_basic_context_test.xml

- https://github.com/naver/arcus-spring/issues/65
- 인자가 없는 생성자를 deprecate 시켜 사용하지 않도록 권장합니다. 대신 필수 인자를 입력해야 하는 생성자를 제공합니다.
- 반드시 내부에서만 사용되어야 하는 필드인 keyLockProvider를 제외하고는 모두 configuration을 통해 접근하도록 변경했습니다.
- 이를 통해 필수 인자가 아닌 옵션들의 검증은 ArcusConfiguration 한 군데에서만 거치면 됩니다. setter, getter도 ArcusCache 클래스에서 제공해줄 필요가 없습니다.
- 참고로 redis, couchbase도 XXXCache 클래스에 XXXCacheConfiguration 클래스를 필드로 두고 있습니다.

 INTERNAL: save configuration instance in ArcusCache

---

README.md
docs/02-arcus-spring-concept.md
docs/03-arcus-spring-usage.md
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheConfigurationTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerBuilderTest.java

- 
- ArcusCacheConfiguration으로 사용자가 값을 설정할 때 setter 대신 withServiceId, enableFrontCaching 등의 메서드를 사용하도록 변경하고 해당 메서드 안에서 입력값을 검증하도록 합니다.
- 사용자 입장에서 코드가 좀 더 간결해진다는 장점이 있으며, Redis와 Couchbase와 비슷한 방식으로 사용할 수 있습니다.
- setter를 deprecate시키기 때문에, 나중에 setter가 제거되면 xml으로 ArcusCacheConfiguration의 각 필드를 설정할 수 없게 됩니다. 반드시 xml 빈 등록 방식을 지원해야 한다면 ArcusCacheConfigurationFactoryBean 클래스를 만들고 이 안에 setter를 두면 xml기반 설정 방식을 지원할 수 있습니다. 의견 부탁드립니다.
- 기존 ArcusCache에 있던 기본값들을 ArcusCacheConfiguration에서 더 많이 사용하므로 옮겼습니다.

INTERNAL: provide meaningful methods instead of setters in ArcusCacheConfiguration

---

docs/02-arcus-spring-concept.md
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- https://github.com/jam2in/arcus-works/issues/564
- wantToGetException의 deprecation 을 제거하고 부활합니다.
- InterruptedException 발생 시에는 항상 예외를 발생하도록 합니다.

INTERNAL: remove deprecation of wantToGetException

---

src/main/java/com/navercorp/arcus/spring/ArcusClientFactoryBean.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
src/main/java/com/navercorp/arcus/spring/cache/SimpleStringKeyGenerator.java
src/main/java/com/navercorp/arcus/spring/cache/StringKeyGenerator.java
src/main/java/com/navercorp/arcus/spring/cache/front/EhArcusFrontCache.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java

- https://github.com/jam2in/arcus-works/issues/492
- `javax.annotation.Nullable` -> `org.springframework.lang.Nullable` 로 변경합니다.

INTERNAL: change dependency of `@Nullable` to spring framework

---

src/test/java/com/navercorp/arcus/spring/ApplicationContextLoadTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheWithAnnotationTest.java
src/test/java/com/navercorp/arcus/spring/cache/KeyGeneratorTest.java
src/test/java/com/navercorp/arcus/spring/cache/front/DefaultArcusFrontCacheTest.java
src/test/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProviderTest.java

- 
- junit5로 업그레이드하여 이제 public 접근자를 제거해도 테스트가 수행됩니다.
- testXXX 형태의 테스트 메서드 이름을 이해하기 쉽게 변경했습니다.

TEST: remove public access modifier and rename test methods

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheManager.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheManagerTest.java
src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
src/test/java/com/navercorp/arcus/spring/cache/front/DefaultArcusFrontCacheTest.java
src/test/java/com/navercorp/arcus/spring/concurrent/DefaultKeyLockProviderTest.java
src/test/resources/log4j2.properties

- 
- 다음과 같이 코드를 정리했습니다.
- java 8 문법에 따른 변화 반영 (변수 초기화 시 다이아몬드 연산자`<>`로 변경 / 익명함수 -> 람다로 변경 / 람다 표현식 간결화)
- ArcusCache 생성자에서 deprecated된 setter 사용하지 않도록 변경
- ArcusCacheManager 생성자 간결하게 변경 및 변수를 final 로 선언

CLEANUP: tidy codes

---

src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
src/test/resources/arcus_spring_basic_context_test.xml

- 
- ArcusCache의 주석에 달린 방식은 현재 권장하는 방식이 아니고, 사용 방법은 docs에 충분히 나와있으므로 제거합니다.
- xml에서 ArcusCache의 setter를 사용하던 것을 제거하고 SuppressWarnings을 제거합니다.

CLEANUP: remove redundant SuppressWarnings

---

pom.xml

- 
- Arcus Java Client 의존성에서 제외하지 않아도 되는 의존성이 있어 해당 부분을 제거합니다.
- slf4j-log4j12, slf4j-reload4j 의존성은 ZooKeeper에 의해 생겨나는데, Arcus Java Client에서 ZooKeeper 의존성을 가져올 때 해당 두 의존성을 제외하기 때문에 Arcus Spring에서도 자연스럽게 제외되어있는 형태일 것입니다.

FIX: remove stale dependency in pom.xml

---

src/main/java/com/navercorp/arcus/spring/ArcusClientFactoryBean.java

- https://github.com/naver/arcus-spring/issues/116
- ArcusClientFactoryBean에서 keepalive 옵션을 활성화할 수 있도록 수정합니다.
- +) java client에서 1.14.1 릴리즈 시 ehcache 옵션 설정이 변경될 예정입니다. arcus spring도 릴리즈 전 java client 1.14.1 버전을 사용하도록 변경할텐데, 이 FactoryBean도 함께 수정할 예정입니다.

INTERNAL: support keepalive option in ArcusClientFactoryBean
